name=MPU6500-DMP
version=1.0.0
author=Renzo Mischianti <renzo.mischianti@gmail.com>
maintainer=Renzo Mischianti <renzo.mischianti@gmail.com>
sentence=Driver for InvenSense's MPU-6500 6-DOF IMU (3-axis gyroscope & 3-axis accelerometer) with Digital Motion Processor support
paragraph=The <a href="https://invensense.tdk.com/products/motion-tracking/6-axis/mpu-6500/">MPU-6500</a> is a 6-axis motion tracking device featuring acceleration full-scales of ±2 / ±4 / ±8 / ±16 (g) and rotational full-scales of ±250 / ±500 / ±1000 / ±2000 (°/sec). It includes an I<sup>2</sup>C serial bus interface that supports speeds up to 400 kHz. The DMP provides quaternions, pedometer, tap and orientation detection and gyro calibration. This library is a fork of the SparkFun MPU-9250 DMP one.
category=Sensors
url=https://github.com/xreef/MPU-6500-DMP_Library
repository=https://github.com/xreef/MPU-6500-DMP_Library
architectures=*
includes=MPU6500-DMP.h
